### ISSUE TITLE
HTML Validation issues for heavily-attributed product

### ISSUE THREAD

**Issue by lat9** [chadlly2003/zencart_responsive_classic_redesign#44]
See this link for the HTML validation issues: https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.zencartdemo.com%2Findex.php%3Fmain_page%3Dproduct_info%26cPath%3D22%26products_id%3D34

Coming from this product_info page display: https://www.zencartdemo.com/index.php?main_page=product_info&cPath=22&products_id=34

**Comment by chadlly2003** [comment]
All HTML errors have been fixed site-wide.

**Comment by dbltoe** [comment]
In the files or on the demo site? Still seeing errors on the demo site.

**Comment by chadlly2003** [comment]
hmm which program are you using.  What error are you seeing?  the files in github are the same files on the demo site.

**Comment by chadlly2003** [comment]
i see the issue to be continued

**Comment by chadlly2003** [comment]
This has been fixed i was using the add-on from chrome.  That didn't show all those errors for whatever reason
